SELECT DISTINCT 
OWNER,
TABLE_NAME,
COLUMN_NAME,
DATA_TYPE,
DATA_LENGTH,
NULLABLE
FROM
(SELECT 
OWNER,
TABLE_NAME,
COLUMN_NAME,
DATA_TYPE,
DATA_LENGTH,
NULLABLE
 FROM ALL_TAB_COLS
WHERE 
TABLE_NAME in (:TABLE_NAME)
UNION ALL
SELECT 
ALL_TAB_COLS.OWNER,
ALL_SYNONYMS.SYNONYM_NAME AS TABLE_NAME,
ALL_TAB_COLS.COLUMN_NAME,
ALL_TAB_COLS.DATA_TYPE,
ALL_TAB_COLS.DATA_LENGTH,
ALL_TAB_COLS.NULLABLE
 FROM ALL_TAB_COLS JOIN ALL_SYNONYMS ON ALL_TAB_COLS.TABLE_NAME = ALL_SYNONYMS.TABLE_NAME  
WHERE ALL_SYNONYMS.SYNONYM_NAME IN (:TABLE_NAME)
)